config/routes.rb
SeaCinema::Application.routes.draw do
  resources :movie_models

  get "movies/create"
  get "movies/view"
  get "movies/update"
  get "movies/delete"
  get "movies/viewAll"
  post "movie/create"
  get "movie/get"
  post "movie/update"
  delete "movie/delete"
  get "movie/getAll"

end

app/models/movie_model.rb
class MovieModel < ActiveRecord::Base
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/movie_controller.rb
class MovieController < ActionController::Base
  layout nil
  def create

  end
  def get
    render json: "HELLO"
  end
  def update

  end
  def delete

  end
  def getAll

  end
end

app/controllers/movie_models_controller.rb
class MovieModelsController < ApplicationController
  before_action :set_movie_model, only: [:show, :edit, :update, :destroy]

  # GET /movie_models
  # GET /movie_models.json
  def index
    @movie_models = MovieModel.all
  end

  # GET /movie_models/1
  # GET /movie_models/1.json
  def show
  end

  # GET /movie_models/new
  def new
    @movie_model = MovieModel.new
  end

  # GET /movie_models/1/edit
  def edit
  end

  # POST /movie_models
  # POST /movie_models.json
  def create
    @movie_model = MovieModel.new(movie_model_params)

    respond_to do |format|
      if @movie_model.save
        format.html { redirect_to @movie_model, notice: 'Movie model was successfully created.' }
        format.json { render action: 'show', status: :created, location: @movie_model }
      else
        format.html { render action: 'new' }
        format.json { render json: @movie_model.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /movie_models/1
  # PATCH/PUT /movie_models/1.json
  def update
    respond_to do |format|
      if @movie_model.update(movie_model_params)
        format.html { redirect_to @movie_model, notice: 'Movie model was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @movie_model.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /movie_models/1
  # DELETE /movie_models/1.json
  def destroy
    @movie_model.destroy
    respond_to do |format|
      format.html { redirect_to movie_models_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_movie_model
      @movie_model = MovieModel.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def movie_model_params
      params.require(:movie_model).permit(:title, :releaseDate, :rating, :length, :summary)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/movie_models_helper.rb
module MovieModelsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>SeaCinema</title>
  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/movie_models/_form.html.erb
<%= form_for(@movie_model) do |f| %>
  <% if @movie_model.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@movie_model.errors.count, "error") %> prohibited this movie_model from being saved:</h2>

      <ul>
      <% @movie_model.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :title %><br>
    <%= f.text_field :title %>
  </div>
  <div class="field">
    <%= f.label :releaseDate %><br>
    <%= f.date_select :releaseDate %>
  </div>
  <div class="field">
    <%= f.label :rating %><br>
    <%= f.text_field :rating %>
  </div>
  <div class="field">
    <%= f.label :length %><br>
    <%= f.text_field :length %>
  </div>
  <div class="field">
    <%= f.label :summary %><br>
    <%= f.text_area :summary %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/movie_models/edit.html.erb
<h1>Editing movie_model</h1>

<%= render 'form' %>

<%= link_to 'Show', @movie_model %> |
<%= link_to 'Back', movie_models_path %>

app/views/movie_models/index.html.erb
<h1>Listing movie_models</h1>

<table>
  <thead>
    <tr>
      <th>Title</th>
      <th>Releasedate</th>
      <th>Rating</th>
      <th>Length</th>
      <th>Summary</th>
      <th></th>
      <th></th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @movie_models.each do |movie_model| %>
      <tr>
        <td><%= movie_model.title %></td>
        <td><%= movie_model.releaseDate %></td>
        <td><%= movie_model.rating %></td>
        <td><%= movie_model.length %></td>
        <td><%= movie_model.summary %></td>
        <td><%= link_to 'Show', movie_model %></td>
        <td><%= link_to 'Edit', edit_movie_model_path(movie_model) %></td>
        <td><%= link_to 'Destroy', movie_model, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Movie model', new_movie_model_path %>

app/views/movie_models/new.html.erb
<h1>New movie_model</h1>

<%= render 'form' %>

<%= link_to 'Back', movie_models_path %>

app/views/movie_models/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Title:</strong>
  <%= @movie_model.title %>
</p>

<p>
  <strong>Releasedate:</strong>
  <%= @movie_model.releaseDate %>
</p>

<p>
  <strong>Rating:</strong>
  <%= @movie_model.rating %>
</p>

<p>
  <strong>Length:</strong>
  <%= @movie_model.length %>
</p>

<p>
  <strong>Summary:</strong>
  <%= @movie_model.summary %>
</p>

<%= link_to 'Edit', edit_movie_model_path(@movie_model) %> |
<%= link_to 'Back', movie_models_path %>